### ISSUE TITLE
getting this error OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 6): Library not loaded: @rpath/libvlccore.dylib   Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib   Reason: image not found

### ISSUE THREAD

**Issue by markmark1** [and3rson/clay#51] opened 2018-11-18 18:53 UTC
Traceback (most recent call last):
  File "/usr/local/bin/clay", line 9, in <module>
    load_entry_point('clay-player==1.1.0', 'console_scripts', 'clay')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ckakdsa/Library/Python/2.7/lib/python/site-packages/clay/app.py", line 16, in <module>
    from clay.player import player
  File "/Users/ckakdsa/Library/Python/2.7/lib/python/site-packages/clay/player.py", line 16, in <module>
    from clay import vlc, meta
  File "/Users/ckakdsa/Library/Python/2.7/lib/python/site-packages/clay/vlc.py", line 199, in <module>
    dll, plugin_path  = find_lib()
  File "/Users/ckakdsa/Library/Python/2.7/lib/python/site-packages/clay/vlc.py", line 184, in find_lib
    dll = ctypes.CDLL(p)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 6): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
  Reason: image not found

**Comment by agg23** [comment] 2018-11-22 21:03
Do you have VLC installed? Does the `.dylib` exist at that path?

**Comment by markmark1** [comment] 2018-11-22 21:27
Yes, I do Have it installed
  
  
How do I find if it's available in the path pls Adam thanks so much   
  
  

  
  

  
  
>

**Comment by agg23** [comment] 2018-11-22 21:42
Navigate to /Applications/VLC.app, right click on it and choose "View Package Contents" (or something to that effect). Navigate to Contents/MacOS/lib/ and make sure `ibvlccore.dylib` exists. I would check for you (at least in the standard VLC distribution for macOS), but I don't have easy access to a Mac right now.

There are two things I would try. First, you're using Python 2.7, whereas Clay is designed for Python 3 and up. Second, Clay has been largely rewritten on the `porcelain` branch. You should probably try that out and see if it works.

**Comment by ValentijnvdBeek** [comment] 2018-11-22 22:58
Hi everyone, sorry for being a tad late. I have been a bit busy with school lately. 

First things first, this is a duplicate of #28 and the problem basically boils down to the fact that none of Clay's contributors run any operating system besides GNU/Linux so any other operating are, sadly, entirely unsupported. Any help wanted in actively testing and contributing in this fields would be greatly appreciated. 

> First, you're using Python 2.7, whereas Clay is designed for Python 3 and up.

Adam please don't say that so loud before @and3rson hears you and yells at me about it. Support Python for versions before v3.4[1] has only been dropped in the `porcelain` branch and I haven't had the chance to discuss it with him yet so it might reverted. It is true that is a pretty much a second citizen platform.

> Second, Clay has been largely rewritten on the porcelain branch.

This _might_ work since `porcelain` now supports using MPV instead of VLC which _might_ not have the same problem. The following setting should enable it:
```
clay_settings:
   player_class: clay.playback.mpv:MPVPlayer
```

Anyways, thanks Mark for reporting the issue and thanks a lot to you Adam for stepping, I appreciate it. I'll give you guys some time to respond but I'll be closing this issue in a few days since it a duplicate, nothing personal. Pinkie promise.

EDIT: happy thanksgiving btw, enjoy the turkey

[1] Picked because it is the version that the oldest Ubuntu LTS has which makes sense to me since Clay is an user application.

**Comment by agg23** [comment] 2018-11-23 00:13
> Support Python for versions before v3.4 has only been dropped in the porcelain branch
 
Interesting. The README has stated 3.x up since the second commit to the repo.

If I get time, I might look into what needs to be done to make it work in macOS.

**Comment by markmark1** [comment] 2018-11-23 00:19
Pls do need clay on macOS … you guys are amazing

**Comment by markmark1** [comment] 2018-11-23 00:20
Thanks valentjin
You are great
How do I know if I have mpv

**Comment by markmark1** [comment] 2018-11-23 00:32
Cant install now ython/2.7/site-packages/mutagen/oggvorbis.py to oggvorbis.pyc
byte-compiling /Library/Python/2.7/site-packages/mutagen/optimfrog.py to optimfrog.pyc
byte-compiling /Library/Python/2.7/site-packages/mutagen/_tags.py to _tags.pyc
byte-compiling /Library/Python/2.7/site-packages/mutagen/aac.py to aac.pyc
running install_data
creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-KO_CsB/mutagen/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-6Oxln_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-KO_CsB/mutagen/
mark@marks-MacBook-Air-2 ~ $ sudo pip install clay-player
The directory '/Users/mark/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mark/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting clay-player
Downloading https://files.pythonhosted.org/packages/32/2f/fe2ecb42d98020723649b5a8d6a5cdb41a14546e593c0fe1415441023755/clay-player-1.1.0.tar.gz (221kB)
100% |################################| 225kB 8.2MB/s
jCollecting gmusicapi (from clay-player)
Downloading https://files.pythonhosted.org/packages/4d/7b/bd10a13c6b24f72c16ce0e81c40250b1e97f2da62a0ba0763fc99456a063/gmusicapi-11.0.4.tar.gz (170kB)
100% |################################| 174kB 11.1MB/s
Requirement already satisfied: PyYAML in /Library/Python/2.7/site-packages (from clay-player) (3.13)
Collecting urwid (from clay-player)
Downloading https://files.pythonhosted.org/packages/c7/90/415728875c230fafd13d118512bde3184d810d7bf798a631abc05fac09d0/urwid-2.0.1.tar.gz (604kB)
100% |################################| 614kB 9.9MB/s
Collecting codename (from clay-player)
Downloading https://files.pythonhosted.org/packages/c8/44/682d39480678b0d3a07c7c7c08e5c102e4807938ed9d126a77e21be00afd/codename-1.1.tar.gz
Requirement already satisfied: validictory!=0.9.2,>=0.8.0 in /Library/Python/2.7/site-packages (from gmusicapi->clay-player) (1.1.2)
Requirement already satisfied: decorator>=3.3.1 in /Library/Python/2.7/site-packages (from gmusicapi->clay-player) (4.3.0)
Collecting mutagen>=1.34 (from gmusicapi->clay-player)
Downloading https://files.pythonhosted.org/packages/c0/17/e1c3c18f5d637ebebcb94aa19d74c8c06925cb4ffb9f1031fe5f21a698d3/mutagen-1.41.1.tar.gz (918kB)
100% |################################| 921kB 9.6MB/s
C

**Comment by markmark1** [comment] 2018-11-23 00:33
ore.dylib
Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
Reason: image not found
mark@marks-MacBook-Air-2 ~ $ unset PYTHONPATH;clay
Traceback (most recent call last):
File "/usr/local/bin/clay", line 11, in <module>
load_entry_point('clay-player==1.1.0', 'console_scripts', 'clay')()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
return ep.load()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
return self.resolve()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/lib/python3.7/site-packages/clay/app.py", line 16, in <module>
from clay.player import player
File "/usr/local/lib/python3.7/site-packages/clay/player.py", line 16, in <module>
from clay import vlc, meta
File "/usr/local/lib/python3.7/site-packages/clay/vlc.py", line 199, in <module>
dll, plugin_path = find_lib()
File "/usr/local/lib/python3.7/site-packages/clay/vlc.py", line 184, in find_lib
dll = ctypes.CDLL(p)
File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 6): Library not loaded: @rpath/libvlccore.dylib
Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
Reason: image not found
mark@marks-MacBook-Air-2 ~ $

**Comment by ValentijnvdBeek** [comment] 2018-11-23 13:35
@agg23 

Apparently it does yeah but our CI does test whether it works for [Python 2](https://travis-ci.org/and3rson/clay/jobs/414017161), our Github has the Python 2 tag and [the code is written so it works in  Python 2](https://github.com/and3rson/clay/blob/master/clay/player.py). In fact the only reason why I decided to drop it in the `porcelain` branch was because the way we did enums was rather messy.

@markmark1 

When I said that it is a duplicate issue and that I am going to close it soon it means that you're supposed to subscribe to that issue instead since you won't be able to post to this one anymore. 

Also, you need some work on your posting etiquette. I appreciate your enthusiasm but you're slightly misunderstanding the way that these issues work. They aren't really a real time chat system like IRC, WhatsApp or Facebook messenger but they are more like a forum or an email. So please take your time with responding, do your own research in the meantime and edit your previous messages when you have something more to add instead of sending a new one. Getting five emails where one was enough is slightly annoying. 

If you do want something more in that style then I would recommend that you use our IRC channel (#clay at irc.oftc.net) or our Matrix room (#clay:matrix.org) instead (despite having like four people on there).

**Closed as completed** 2018-11-28 12:24 UTC

**Comment by markmark1** [comment] 2018-11-28 14:27
Got it, thank you. This is a good project   
  
  
  

  
  

  
  
>
